steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ["install"]
    dir: "frontend-gatsby"
  - name: 'gcr.io/cloud-builders/yarn'
    args: ["build"]
    dir: "frontend-gatsby"
  - name: "node:10.18.1"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "$PROJECT_ID", "--token", "$_TOKEN", "--only", "hosting"]
    dir: "frontend-gatsby"