steps:
  - name: node:10.18.1 
    entrypoint: yarn
    args: ["install"]
    dir: "frontend-gatsby"
  - name: node:10.18.1
    entrypoint: yarn
    args: ["build"]
    dir: "frontend-gatsby"
  - name: "node:10.18.1"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "$PROJECT_ID", "--token", "$_TOKEN", "--only", "hosting"]
    dir: "frontend-gatsby"